name: Update manifest version

on:
  release:
    types: [published]

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
	with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # wichtig für Commit & Push

      - name: Extract version from release tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF##*/}
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Update manifest.json version
        run: |
          jq '.version = "${{ steps.get_version.outputs.version }}"' custom_components/plantbot/manifest.json > tmp.json
          mv tmp.json custom_components/plantbot/manifest.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update manifest version to ${{ steps.get_version.outputs.version }}" || echo "No changes to commit"

      - name: Push changes to main
        run: |
          git push origin HEAD:main

