name: Update manifest version

on:
  release:
    types: [published]

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken mit Schreibrechten
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # 2️⃣ Version aus dem Release-Tag extrahieren (entfernt führendes "v")
      - name: Extract version from release tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF##*/}
          VERSION=${VERSION#v}
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # 3️⃣ Version in manifest.json schreiben
      - name: Update manifest.json version
        run: |
          jq '.version = "${{ steps.get_version.outputs.version }}"' custom_components/plantbot/manifest.json > tmp.json
          mv tmp.json custom_components/plantbot/manifest.json

      # 4️⃣ Änderungen committen
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add custom_components/plantbot/manifest.json
          git commit -m "Update manifest version to ${{ steps.get_version.outputs.version }}" || echo "No changes to commit"

      # 5️⃣ Push mit Token, um Authentifizierungsfehler zu vermeiden
      - name: Push changes to main
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main

